export const COLORS = [
  { name: 'Crimson', hex: '#DC143C' },
  { name: 'Coral', hex: '#FF6B6B' },
  { name: 'Peach', hex: '#FFAB76' },
  { name: 'Golden', hex: '#FFD700' },
  { name: 'Sunshine', hex: '#FFF176' },
  { name: 'Mint', hex: '#98FF98' },
  { name: 'Forest', hex: '#228B22' },
  { name: 'Sky', hex: '#87CEEB' },
  { name: 'Ocean', hex: '#006994' },
  { name: 'Lavender', hex: '#967BB6' },
  { name: 'Violet', hex: '#8B00FF' },
  { name: 'Dusty Rose', hex: '#DCAE96' },
  { name: 'Mauve', hex: '#E0B0FF' },
  { name: 'Ivory', hex: '#FFFFF0' },
  { name: 'Warm Orange', hex: '#FF8C00' },
  { name: 'Teal', hex: '#008080' },
  { name: 'Soft Pink', hex: '#FFB6C1' },
];

export const ADJECTIVES = [
  'Joyful',
  'Calm',
  'Grateful',
  'Hopeful',
  'Excited',
  'Proud',
  'Content',
  'Anxious',
  'Stressed',
  'Tired',
  'Sad',
  'Overwhelmed',
  'Other',
];
